# Generated by Django 5.2.12 on 2026-04-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='price',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='price',
        ),
        migrations.AddField(
            model_name='activity',
            name='max_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='min_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='max_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='min_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='max_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='min_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.FloatField(default=1),
        ),
    ]
