# Generated by Django 5.2.12 on 2026-05-06 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_restaurant_tags'),
        ('core', '0003_alter_itineraryitem_options_itineraryitem_created_at'),
    ]

    operations = [
    ]
