# Generated by Django 5.2.12 on 2026-04-30 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_activity_id_alter_hotel_id_alter_restaurant_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='max_price',
            new_name='base_price',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='max_price',
            new_name='base_price',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='max_price',
            new_name='base_price',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='min_price',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='min_price',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='min_price',
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='stars',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='SavedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_type', models.CharField(max_length=20)),
                ('place_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
