# Generated by Django 6.0 on 2026-05-06 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_hotel_image'),
        ('core', '0004_merge_20260506_0449'),
    ]

    operations = [
    ]
