# Generated by Django 5.2.12 on 2026-05-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_likedplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cuisine_tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
